start_measure:
  fields:
    device_id:
      required: true
      example: "abc123def456"
      selector:
        device:
          integration: liquid_check

restart:
  fields:
    device_id:
      required: true
      example: "abc123def456"
      selector:
        device:
          integration: liquid_check
