name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release archive
        run: |
          cd custom_components
          zip -r ../liquid_check.zip liquid_check/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: liquid_check.zip
          generate_release_notes: true
          draft: false
          prerelease: false
